algoritmo "ContarAteQuanto?"
var
   Q, cont: inteiro
inicio
      escreva("Vou contar de um em um, até que número devo contar? ")
      leia (Q)
      escreval
      escreval (Q,"? ......OK! VAMOS LÁ!")
      cont <- 1
           Enquanto (cont <= Q) faca
                    escreval (cont)
                    cont <- (cont + 1)
           FimEnquanto
           escreval
           escreval ("Pronto! Terminei!!")
           escreval
      

fimalgoritmo
