algoritmo "Delta"
// Função :
// Autor :
// Data : 05/09/2020
// Seção de Declarações 
var
a, b, c, delta: real
inicio
escreval ("PREENCHA OS CAMPOS PARA DESCOBRIR O VALOR DE DELTA")
escreval
escreva ("Digite o valor de (a): ")
leia (a)
escreva ("Digite o valor de (b): ")
leia (b)
escreva ("Digite o valor de (c): ")
leia (c)
delta <- ((b^2)-4*a*c)
escreva ("O VALOR DE DELTA É =",delta)
fimalgoritmo
